### ISSUE TITLE
maxFDR for snps significant in both traits

### ISSUE THREAD

**Issue by arkyl** [JonJala/mtag#112]
Hi,
Thanks for this software. 

I am wondering if there is a way to calculate the maxFDR, only for snps that are significant at a threshold, e.g 1e-05, for both of my two traits. Intuitively, this seems to correspond to the fdr on the prob_grid (0 0 0 1). But is there a way to get an accurate number?

I can't simply select the snps that are <1e-05 in both mtag results. One of them has >0.15 maxFDR after I set the threshold to 1e-05. I think for snps that are <1e-05 in both mtag results, their FDR should be lower.

Thanks,
Yue

**Comment by paturley** [comment]
Hello Yue,

I think restricting to SNPs above a certain threshold will violate the
maxFDR model because maxFDR assumes that the distributions of SNP effects
follow a spike and slab distribution and restricting SNPs by p-value to
produce some sort of bimodal distribution where the SNPs with small effect
sizes hollowed out.

I'm not sure how you would use the framework programmed into the MTAG
software to get at what you want. It'd different enough from the simple
case that it already does that you'd likely need to revise the existing
code.

Sorry I can't be more helpful.

Best,
Patrick

**Comment by arkyl** [comment]
Hi Patrick,
Thanks very much for the reply.

I think I may misunderstand the fdr on the prob_grid. 
For two traits mtag, if I have a snps of pvals in two traits as 1e-07 and 1e-08, doesn't this at least infer that the prob_grid is very unlikely to be (False,False). So I may search for the max FDR only in the space of prob_grid, where prior of (False,False) is very low? For example, remove the prob_grid such as (0.8,0.1,0.1,0.0).

In a related question, now I simply count the snps that are both significant in the mtag of two traits, and I found a case like this:
trait1 gwas pval and N:  0.504227216646 71639
trait2 gwas pval and N: 1.775e-69 842557
mtag_pval for trait1: 5.67259013825425e-12.
The trait1 mtag_pval significance increases from 0.504 to 5.67259013825425e-12, probably due to its highly significance in trait2 as 1.775e-69 and much larger sample size in trait2.  Should I be cautious for such case?

Thanks,
Yue

**Comment by paturley** [comment]
Hello Yue,

The maxFDR calculation doesn't actually look at individual SNPs when it
does it's calculation. It it based entirely on the estimated Omega and
Sigma matrices. It then searches over possible scenarios with different
fractions of jointly associated or uniquely associated SNPs, calculating
the expected FDR for each of them, and tells you the maximum FDR it
calculated. So removing the (0.8,0.1,0.1,0.0) prob grid point doesn't
correspond to dropping low-significance SNPs (since dropping those SNPs
would also affect Omega and Sigma). It instead corresponds to an assumption
that there is no way that 80% of the SNPs in your data are both not
actually associated with the outcome, that 10% of the SNPs are associated
with one trait but not the other (for each trait), and that no SNPs are
associated with both traits. This may be a reasonable assumption in your
setting, but you should be aware that it is an assumption.

There is always a risk that MTAG may pull through signal for a SNP that is
associated with one phenotype and not the other (which is why we recommend
the maxFDR calculations), but just because the p-value is large for one
trait, that doesn't mean that the MTAG association is certainly spurious.
The p-value could be large just because you have a much smaller sample
size, for example.

Best,
Patrick

**Comment by arkyl** [comment]
Thanks a lot for your detailed and clear explanation.  Please close the issue.
