### ISSUE TITLE
WARNING: 56 SNPs had P outside of (0,1].

### ISSUE THREAD

**Issue by FlippedYao** [JonJala/mtag#201]
I am sure my P column is correctly labeled. May be it is because the P value in these variant is too small (<1e-300 I guess).
So what should I do？Should I set these P to 1e-299? There have any better solutions?

**Comment by paturley** [comment]
That's a tough question.

Seems like you can either drop those SNPs or adjust them like you say. Both
options would likely lead to biases in the final output, but if it's only
56 SNPs, I suspect the bias will be small. My gut instinct is to drop them
from the MTAG analysis since included adjusted P-values will lead to
potentially large bias in the final beta coefficients (in addition to the
small bias in the Omega and Sigma matrices, which will be a problem with
both approaches). Once you have those estimates, you can either just add
the 56 SNPs back in (annotating them as GWAS estimates rather than MTAG
estimates) or you can used the estimated Omega and Sigma matrices from the
MTAG log to calculate the MTAG estimates for those 56 SNPs manually using
functions that don't have the underflow problems of MTAG. While the former
won't maximize the power for those SNPs, since they already have p-values
less than 1e-300, probably that's not such a big deal).

**Comment by FlippedYao** [comment]
Thank you very much for your help, wish you have a good day!
