### ISSUE TITLE
Questions about Sample Size and --std_betas

### ISSUE THREAD

**Issue by nvice111** [JonJala/mtag#212]
Hello, I have a few questions:

1. The first question is about the sample size (n) input in GWAS: “snpid chr bpos a1 a2 freq z pval n”
I would like to confirm the following assessments with you, and please point out any inaccuracies:
(1) For binary variables, such as diabetes, GWAS uses a logistic model. Is the sample size (n) calculated actually using the effective sample size formula = 4N_cases*N_controls/(N_cases + N_controls) correct?
(2) For continuous variables, such as FSH levels, GWAS uses a linear model, and n is the original total sample size or the sample size given for each SNP, right?
(3) For some ordinal variables, such as Number of pregnancies, or smoking (sometimes assessed in three categories: never, former, now), they are generally treated as continuous variables using a linear model, and n is the original total sample size or the sample size given for each SNP. Do you know if there are other models used to conduct GWAS, resulting in the need to use an effective sample size?
2. Regarding --std_betas
Before or after using this parameter, can the **unit** of mtag_beta be interpreted as:
For binary variables, per log(OR)
For continuous variables, such as per S.D.
For some ordinal variables, per S.D.
Or how should it be interpreted before or after using this parameter --std_betas and when should we use --std_betas?  Is it better to use --std_betas in MTAG ? This is important for interpreting results in mendelian randomization.
3. How does MTAG handle gender differences, for example, mixing gestational diabetes (only female) and glycated hemoglobin (female and male)?
4. When MTAG outputs files, is the new sample size for each trait calculated using GWAS equiv. (max) N? Can this new sample size （ GWAS equiv. (max) N） be used for subsequent analyses that require sample size information?
5. When inputting files into MTAG, if I choose to only input "snpid chr bpos a1 a2 freq z pval n" and not beta and se values, is the z-value calculated using the z=beta/se values from the original GWAS?
6. When using the Z-N option, you mentioned in a previous issue (#97) that "Z/sqrt(N) is a good approximation of the marginal effect size for a SNP in standard deviation units for the genotype and phenotype." Is the formula to obtain the standardized beta like this: beta = zscore / sqrt(2freq(1-freq)*(n+zscore^2))? not beta=Z/sqrt(N) in MTAG?
7. 
Thank you !

**Comment by paturley** [comment]
All good questions. For your sample size questions, the N is supposed to be
a proxy for the (inverse) magnitude of the SE(-squared). So

1. For binary traits estimated using logistic regression, I would use the
effective sample size.
2. For continuous traits, I would use the number of individuals to estimate
the association for the specific SNP, though the original total sample size
is probably fine in most cases if the SNP level sample size isn't available.
3. If the model is estimated using OLS (which is what I think you referred
to as a linear model), you just just use the actual sample size. No need
for an adjustment.

Re --std_betas: This option is about whether the genotypes are standardized
or not, not about whether the phenotypes are standardized. MTAG output
always corresponds to standardized phenotypes. For results based on
logistic regression, this should be fine since the underlying latent
parameter is assumed to have variance one. For OLS based results, the units
of the output will be standard deviations of the phenotype per allele (or
standard deviations of the phenotype per standard deviation of the genotype
if you use the --std_betas options.)

Re gender differences: MTAG just looks at the empirical correlation between
the effect sizes for the two traits uses the genome-wide correlation to
boost power at each SNP. So it's effectively blind to the phenotypes used.
So even if one phenotype is only measured in females, MTAG should produce
estimates that still correspond to females when it's done even if other
phenotypes have males and females (conditional on satisfying MTAGs
assumptions).

**Comment by nvice111** [comment]
I updated the question earlier, maybe the email didn't get to you. I'd like to ask you again, thank you very much!

1. The first question is OK
2. Regarding --std_betas,I am still unclear about something: I know is  about the output beta
Before or after using this parameter, can the **unit** of mtag_beta be interpreted as:
For binary variables,   per log(OR) of the phenotype per allele change (no --std_betas), per log(OR) of the phenotype per standard deviation of the genotype (use --std_betas)  . 
Is it correct? 
For continuous variables: SD of the phenotype per allele change (no --std_betas)  SD of the phenotype per standard deviation of the genotype (use --std_betas)
For some ordinal variables: SD of the phenotype per allele  change(no --std_betas)  SD of the phenotype per standard deviation of the genotype (use --std_betas)

(1)Or how should it be interpreted before and  after using this parameter --std_betas ? 
(2)and what's the per standard deviation of the genotype mean?
(3)when should we use --std_betas?  
(4)Is it better to use --std_betas in MTAG ? This is important for interpreting results in mendelian randomization.
3. This queation is OK :How does MTAG handle gender differences, for example, mixing gestational diabetes (only female) and glycated hemoglobin (female and male)?
4. When MTAG outputs files, is the new sample size for each trait calculated using GWAS equiv. (max) N? Can this new sample size （ GWAS equiv. (max) N） be used for subsequent analyses that require sample size information?
5. When inputting files into MTAG, if I choose to only input "snpid chr bpos a1 a2 freq z pval n" and not beta and se values, is the z-value calculated using the z=beta/se values from the original GWAS?
6. When using the Z-N option, you mentioned in a previous issue (#97) that "Z/sqrt(N) is a good approximation of the marginal effect size for a SNP in standard deviation units for the genotype and phenotype." Is the formula to obtain the standardized beta like this: beta = zscore / sqrt(2freq(1-freq)*(n+zscore^2))? not beta=Z/sqrt(N) in MTAG?

Thank you very much for answering my question again！

**Comment by nvice111** [comment]
I updated the question earlier, maybe the email didn't get to you. I'd like to ask you again, thank you very much! The question is above, thank you very much for your answer!

**Comment by paturley** [comment]
Apologies for the slow response here. Responses below:

2) Your interpretation sounds right to me. What I mean by "standard deviation of a genotype" I mean x/std(x) where x is the 0/1/2 measure of the genotype. There is essentially no reason that I think you'd ever need the --std-beta option. I'm not sure why we included it.

4) GWAS-equivalent N is meant as an "effective N" measure that could be used in later analyses.

5) yes, Z = beta/se

6) I don't understand what you mean by this question. Where did you get your alternative formula?

**Comment by nvice111** [comment]
Thank you very much for your response. Let me add to my question:

1. Regarding the previous issue "When using the Z-N option, you mentioned in a previous issue (#97) that 'Z/sqrt(N) is a good approximation of the marginal effect size for a SNP in standard deviation units for the genotype and phenotype.' Is the formula to obtain the standardized beta like this: beta = zscore / sqrt(2freq(1-freq)*(n+zscore^2))? not beta=Z/sqrt(N) in MTAG?"
The formula beta = zscore / sqrt(2freq(1-freq)*(n+zscore^2)) comes from https://www.nature.com/articles/ng.3538. The specific description is as follows:
<img width="587" alt="image" src="https://github.com/JonJala/mtag/assets/124003248/431b4e5b-140a-43fb-820f-97ffba7e9b0c">

In a previous issue (#97), you mentioned that the effect size for a SNP is calculated using Z/sqrt(N). However, this seems different from the method I learned from other papers for calculating the beta value. Is this a similar estimate?

2. Since GWAS-equivalent N is meant as an effective N, is there a way to estimate the new case/control ratio? (It seems that this cannot be deduced from the formula.) Or is it more appropriate to use the original GWAS case/control ratio for like colocalization studies which need ?   
3. 
The formula for effective sample size seems to differ. In MTAG, should we use this one (Neff = 4N_cases * N_controls / (N_cases + N_controls)) instead? I'm not entirely sure about the differences, as it seems they are based on different assumptions.
When assuming Case:Control = 1:1,
Neff = 4N_cases * N_controls / (N_cases + N_controls).
When assuming different case/control ratios, as mentioned in Nature Protocols (https://www.nature.com/articles/nprot.2014.071),
Neff = 2N_cases * N_controls / (N_cases + N_controls).
<img width="470" alt="image" src="https://github.com/JonJala/mtag/assets/124003248/6d88eb01-1616-4778-95d3-64b009bb294b">

4. I want to confirm again, if we don't use --std_betas, then the unit is the SD of the phenotype per allele change. Generally, other GWAS also use this unit, SD of the phenotype per allele change. This makes it easier to interpret the results in Mendelian randomization studies, as both are based on per allele change. For example, an increase of one SD in blood glucose results in an increase of one SD in BMI. So, not using --std_betas is appropriate.

**Comment by paturley** [comment]
1) Ah, I see. Your formula will be better than mine, though they should be pretty close if the effect size of the SNP is small. Feel free to use yours then.

2) I presume that the implicit effective case/control ratio of the new MTAG results will be the same as in the original GWAS sumamry statistics since you can interpret MTAG coefficients as "what if I went out and gathered a sample using the same sampling scheme but in a larger sample?" But I haven't tested it, so I can't totally vouch that this works.

3) We recommended the effective N based on what we understood the standard procedure to be from the literature. If you have a formula for effective N that you think is better suited to your case, you should use that.

4) Yes, I believe that your interpretation is right.
